[package]
name = "blazing-chat"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
sqlx = { workspace = true }
blazing-models = { workspace = true }
serde_json = { workspace = true }
axum = { workspace = true }
blazing-auth = { workspace = true }