[package]
name = "blazing-server"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
axum = { workspace = true }
sqlx = { workspace = true }
blazing-auth = { workspace = true }
tokio = { workspace = true }
dotenvy = { workspace = true }